### ISSUE TITLE
int parses to instant

### ISSUE THREAD

**Issue by abdelgadir** [Synt4xErr0r4/json5#3]
hi

thanks for the lib
i tried  to parse  the below but the newerThan field is being parsed to Instant instead of int

{
  specs: [
    {
      from: "xxxx@xx.co.uk",
      s3Bucket: "xxxx",
      jobs: [
        {
          description: "xxxx",
          s3Destination: "xxxx",
          folder: "Inbox",
          filter: {
            combiner: "AND",
            //in days
            **newerThan**: 30,
            subject: "test subject 9",
            "from": "xxx.co.uk"
          },
          onFailure: {
            copyTo: "failure_archive",
            delete: false
          },
          onSuccess: {
            copyTo: "success_archive",
            delete: false
          }
        }
      ]
    }
  ]
}

![image](https://github.com/Synt4xErr0r4/json5/assets/1619351/ef8c9bf5-f836-4aa3-ace3-b8590ac4a4da)

**Comment by Synt4xErr0r4** [comment]
Yes, ints are parsed as Instants by default. I will change this in the next version, that was actually not intended to be true by default.
For now, you can add the following to your main or in a static{} block:

```java
JSONOptions.setDefaultOptions(JSONOptions.builder().parseInstants(false).build());
```

**Comment by abdelgadir** [comment]
> Yes, ints are parsed as Instants by default. I will change this in the next version, that was actually not intended to be true by default. For now, you can add the following to your main or in a static{} block:
> 
> ```java
> JSONOptions.setDefaultOptions(JSONOptions.builder().parseInstants(false).build());
> ```

thank you
