### ISSUE TITLE
maven dependency

### ISSUE THREAD

**Issue by abdelgadir** [Synt4xErr0r4/json5#4]
hi
is there a reason why this library is not available from maven central ?
our nexus environment is configured to only proxy maven central and will need changing if we were to use this library.

thanks

**Comment by Synt4xErr0r4** [comment]
No, there's no real reason. I just haven't bothered setting it up yet. I use my own repo for my personal and nightly builds, so I just published it there.

I'll take a look and try to publish it on Maven Central later today.

**Comment by abdelgadir** [comment]
thanks, much appreciated

**Comment by Synt4xErr0r4** [comment]
The repo is now also available from Maven Central: [https://central.sonatype.com/artifact/at.syntaxerror/json5/2.0.0](https://central.sonatype.com/artifact/at.syntaxerror/json5/2.0.0)
